name: Go Mod Tidy

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-mod.yml'
  pull_request:
    branches: [ main, develop ]

jobs:
  go-mod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Check go mod
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum || (echo "go.mod or go.sum is not tidied" && exit 1)

